spring:
  datasource:
    #    url: jdbc:h2:tcp://localhost/~/study/inflearn/h2DB/springdatajpa/springdatajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~
  data:
    web:
      pageable:
        default-page-size: 15
        max-page-size: 2000
#        one-indexed-parameters: true
server:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
    #        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
